command: ["streamlit", "run", "app.py"]
env:
  - name: CHAT_LLM
    valueFrom: chat-llm
  - name: MODEL_ENDPOINT
    valueFrom: model-endpoint
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: CATALOG
    value: "kauvey_poc"
  - name: SCHEMA
    value: "gold"
